-- Neon schema (off-chain data) - mirrors the former Supabase tables:
--   public.requests, public.offers
-- Applied once via: neonctl sql --connection-string "$DATABASE_URL" -f sql/schema.sql

create table if not exists public.requests (
  id           integer not null
               constraint requests_pkey primary key,
  content_hash text    not null,
  requester    text    not null,
  title        text    not null,
  description  text    not null default '',
  reward       text    not null,
  token        text    not null,
  status       smallint not null default 0,
  created_at   timestamptz not null default now()
);

create index if not exists requests_content_hash_idx
  on public.requests using btree (content_hash);

create table if not exists public.offers (
  id            integer not null generated by default as identity
                constraint offers_pkey primary key,
  request_id    integer not null
                constraint offers_request_id_fkey references public.requests (id),
  seller        text    not null,
  ipfs_cid      text    not null,
  encrypted_key text    not null,
  file_name     text    not null,
  file_type     text    not null,
  created_at    timestamptz not null default now()
);

create index if not exists offers_request_id_idx
  on public.offers using btree (request_id);

-- Least-privilege role used by the app at runtime.
-- Grant only what the API routes need. Migrations/DDL run as the owner.
grant select, insert, update
  on public.requests
  to app_user;

grant select, insert, update
  on public.offers
  to app_user;

grant usage, select on sequence public.offers_id_seq to app_user;